version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm


  php-fpm:
    container_name: php-fpm
    build: ./docker
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'db'
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'db'
    volumes:
      - './docker/initdb.d/install.sql:/docker-entrypoint-initdb.d/install.sql'
      - mysql:/var/lib/mysql
    ports:
      - '33006:3306'
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./src:/app
    command: composer install --ignore-platform-reqs
volumes:
  mysql: